# Site settings
ref: CSCC69
title: Operating systems
edition: Summer 2025
description: "Principles of operating systems. The operating system as a control program and as a resource allocator. The concept of a process and concurrency problem: synchronization, mutual exclusion, deadlock. Additional topics include memory management, file systems, process scheduling, threads, and protection."
website: https://thierrysans.me/CSCC69/
github: https://github.com/ThierrySans/CSCC69
piazza: https://piazza.com/utoronto.ca/summer2025/cscc69
feedback: https://forms.gle/MKeNGv2hsxT6nxb49

instructor:
  name: Thierry Sans
  email: "thierry.sans@"
  website: https://thierrysans.github.io/
  hours: Fri 10-11 AM
  location: IA 4124
  contact: Piazza only (no email)

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Chris Lin
      contact: Piazza
      hours: Tue 11 AM
      location: IA 3180 (CS Help Center)
    - name: Hriday Algh
      contact: Piazza
      hours: Thu 5-6 PM
      location: IA B1010
    - name: Sadra Setarehdan
      contact: Piazza
      hours: Wed 1 PM
      location: IA 3180 (CS Help Center)
  
timings:
    - section: LEC01
      time: Fri 11 AM - 1 PM
      location: IA 2150 A
      instructor: Thierry
    - section: TUT01
      time: Mon 3-4 PM
      location: IA 2040
      instructor: Sadra
    - section: TUT02
      time: Thu 4-5 PM
      location: IA B1010
      instructor: Hriday
    - section: TUT05
      time: Mon 2-3 PM
      location: IA 2040
      instructor: Chris
        
first: 20250505